<?php

/**
 * This is the model base class for the table "stats".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Stats".
 *
 * Columns in table "stats" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $datestring
 * @property string $money_voucher_in
 * @property string $money_voucher_out
 * @property string $money_ekr_in
 * @property string $money_ekr_out
 * @property string $money_kr_in
 * @property string $money_kr_out
 * @property string $money_gold_in
 * @property string $money_gold_out
 * @property integer $update_at
 * @property integer $create_at
 *
 */
abstract class BaseStats extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'stats';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Stats|Stats', $n);
	}

	public static function representingColumn() {
		return 'datestring';
	}

	public function rules() {
		return [
			['datestring', 'required'],
			['update_at, create_at', 'numerical', 'integerOnly'=>true],
			['datestring', 'length', 'max'=>255],
			['money_voucher_in, money_voucher_out, money_ekr_in, money_ekr_out, money_kr_in, money_kr_out, money_gold_in, money_gold_out', 'length', 'max'=>19],
			['money_voucher_in, money_voucher_out, money_ekr_in, money_ekr_out, money_kr_in, money_kr_out, money_gold_in, money_gold_out, update_at, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, datestring, money_voucher_in, money_voucher_out, money_ekr_in, money_ekr_out, money_kr_in, money_kr_out, money_gold_in, money_gold_out, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'datestring' => Yii::t('app', 'Datestring'),
			'money_voucher_in' => Yii::t('app', 'Money Voucher In'),
			'money_voucher_out' => Yii::t('app', 'Money Voucher Out'),
			'money_ekr_in' => Yii::t('app', 'Money Ekr In'),
			'money_ekr_out' => Yii::t('app', 'Money Ekr Out'),
			'money_kr_in' => Yii::t('app', 'Money Kr In'),
			'money_kr_out' => Yii::t('app', 'Money Kr Out'),
			'money_gold_in' => Yii::t('app', 'Money Kr Out'),
			'money_gold_out' => Yii::t('app', 'Money Kr Out'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('datestring', $this->datestring, true);
		$criteria->compare('money_voucher_in', $this->money_voucher_in, true);
		$criteria->compare('money_voucher_out', $this->money_voucher_out, true);
		$criteria->compare('money_ekr_in', $this->money_ekr_in, true);
		$criteria->compare('money_ekr_out', $this->money_ekr_out, true);
		$criteria->compare('money_kr_in', $this->money_kr_in, true);
		$criteria->compare('money_kr_out', $this->money_kr_out, true);
		$criteria->compare('money_gold_in', $this->money_gold_in, true);
		$criteria->compare('money_gold_out', $this->money_gold_out, true);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}