<?php

/**
 * This is the model base class for the table "admin_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminHistory".
 *
 * Columns in table "admin_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $admin_id
 * @property integer $action_id
 * @property string $description
 * @property integer $create_at
 *
 */
abstract class BaseAdminHistory extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'admin_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AdminHistory|AdminHistories', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return [
			['admin_id, action_id', 'required'],
			['admin_id, action_id, create_at', 'numerical', 'integerOnly'=>true],
			['description', 'safe'],
			['description, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, admin_id, action_id, description, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'admin_id' => Yii::t('app', 'Admin'),
			'action_id' => Yii::t('app', 'Action'),
			'description' => Yii::t('app', 'Description'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('admin_id', $this->admin_id);
		$criteria->compare('action_id', $this->action_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}