<?php

/**
 * This is the model base class for the table "user_active_balance".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserActiveBalance".
 *
 * Columns in table "user_active_balance" available as properties of the model,
 * followed by relations of table "user_active_balance" available as properties of the model.
 *
 * @property integer $user_id
 * @property integer $price_type
 * @property float $sum_in
 * @property float $sum_out
 * @property float $active_diff
 * @property integer $update_at
 * @property integer $create_at
 *
 * @property User $user
 */
abstract class BaseUserActiveBalance extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_active_balance';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserActiveBalance|UserActiveBalances', $n);
	}

	public static function representingColumn() {
		return 'sum_in';
	}

	public function rules() {
		return [
			['user_id', 'required'],
			['user_id, price_type, update_at, create_at', 'numerical', 'integerOnly'=>true],
			['sum_in, sum_out, active_diff', 'length', 'max'=>19],
			['price_type, sum_in, sum_out, active_diff, update_at, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['user_id, price_type, sum_in, sum_out, active_diff, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
			'user' => [self::BELONGS_TO, 'User', 'user_id'],
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'user_id' => null,
			'price_type' => Yii::t('app', 'Price Type'),
			'sum_in' => Yii::t('app', 'Sum In'),
			'sum_out' => Yii::t('app', 'Sum Out'),
			'active_diff' => Yii::t('app', 'Active Diff'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
			'user' => null,
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('price_type', $this->price_type);
		$criteria->compare('sum_in', $this->sum_in, true);
		$criteria->compare('sum_out', $this->sum_out, true);
		$criteria->compare('active_diff', $this->active_diff, true);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}