<?php

/**
 * This is the model base class for the table "akcii".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Akcii".
 *
 * Columns in table "akcii" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property integer $create_at
 *
 */
abstract class BaseAkcii extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'akcii';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Akcii|Akciis', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return [
			['title', 'required'],
			['create_at', 'numerical', 'integerOnly'=>true],
			['title', 'length', 'max'=>255],
			['id, title, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}