<?php

/**
 * This is the model base class for the table "price_settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PriceSettings".
 *
 * Columns in table "price_settings" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $price_id
 * @property string $dop_ratio
 * @property string $event_limit
 * @property string $strange_output
 * @property integer $auto_output
 * @property string $min_bet
 * @property string $short_name
 * @property integer $update_at
 * @property integer $create_at
 *
 */
abstract class BasePriceSettings extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'price_settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PriceSettings|PriceSettings', $n);
	}

	public static function representingColumn() {
		return 'dop_ratio';
	}

	public function rules() {
		return [
			['price_id', 'required'],
			['price_id, auto_output, update_at, create_at', 'numerical', 'integerOnly'=>true],
			['dop_ratio, event_limit, strange_output, min_bet', 'length', 'max'=>19],
			['short_name', 'length', 'max'=>50],
			['dop_ratio, event_limit, strange_output, auto_output, min_bet, short_name, update_at, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['price_id, dop_ratio, event_limit, strange_output, auto_output, min_bet, short_name, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'price_id' => Yii::t('app', 'Price'),
			'dop_ratio' => Yii::t('app', 'Dop Ratio'),
			'event_limit' => Yii::t('app', 'Event Limit'),
			'strange_output' => Yii::t('app', 'Strange Output'),
			'auto_output' => Yii::t('app', 'Auto Output'),
			'min_bet' => Yii::t('app', 'Min Bet'),
			'short_name' => Yii::t('app', 'Short Name'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('price_id', $this->price_id);
		$criteria->compare('dop_ratio', $this->dop_ratio, true);
		$criteria->compare('event_limit', $this->event_limit, true);
		$criteria->compare('strange_output', $this->strange_output, true);
		$criteria->compare('auto_output', $this->auto_output);
		$criteria->compare('min_bet', $this->min_bet, true);
		$criteria->compare('short_name', $this->short_name, true);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}