<?php

/**
 * This is the model base class for the table "settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Settings".
 *
 * Columns in table "settings" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $min_time_decline
 * @property string $max_percent_decline
 * @property integer $is_daily_limit
 * @property integer $deadline_notify_event
 * @property integer $update_at
 * @property integer $create_at
 *
 */
abstract class BaseSettings extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Settings|Settings', $n);
	}

	public static function representingColumn() {
		return 'dop_ratio';
	}

	public function rules() {
		return [
			['min_time_decline, is_daily_limit, deadline_notify_event, update_at, create_at, min_level', 'numerical', 'integerOnly'=>true],
			['dop_ratio, event_limit_kr, event_limit_ekr, event_limit_voucher, max_percent_decline', 'length', 'max'=>19],
			['min_level, dop_ratio, event_limit_kr, event_limit_ekr, event_limit_voucher, min_time_decline, max_percent_decline, is_daily_limit, deadline_notify_event, update_at, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['min_level, id, dop_ratio, event_limit_kr, event_limit_ekr, event_limit_voucher, min_time_decline, max_percent_decline, is_daily_limit, deadline_notify_event, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'dop_ratio' => Yii::t('app', 'Dop Ratio'),
			'event_limit_kr' => Yii::t('app', 'Event Limit Kr'),
			'event_limit_ekr' => Yii::t('app', 'Event Limit Ekr'),
			'event_limit_voucher' => Yii::t('app', 'Event Limit Voucher'),
			'min_time_decline' => Yii::t('app', 'Min Time Decline'),
			'max_percent_decline' => Yii::t('app', 'Max Percent Decline'),
			'is_daily_limit' => Yii::t('app', 'Is Daily Limit'),
			'deadline_notify_event' => Yii::t('app', 'Deadline Notify Event'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('min_time_decline', $this->min_time_decline);
		$criteria->compare('max_percent_decline', $this->max_percent_decline, true);
		$criteria->compare('is_daily_limit', $this->is_daily_limit);
		$criteria->compare('deadline_notify_event', $this->deadline_notify_event);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}