<?php

/**
 * This is the model base class for the table "sport_event_result".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportEventResult".
 *
 * Columns in table "sport_event_result" available as properties of the model,
 * followed by relations of table "sport_event_result" available as properties of the model.
 *
 * @property integer $event_id
 * @property string $result_field
 * @property integer $value
 * @property integer $create_at
 *
 * @property SportEvent $event
 */
abstract class BaseSportEventResult extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_event_result';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportEventResult|SportEventResults', $n);
	}

	public static function representingColumn() {
		return 'result_field';
	}

	public function rules() {
		return [
			['event_id, result_field, value', 'required'],
			['event_id, value, create_at', 'numerical', 'integerOnly'=>true],
			['result_field', 'length', 'max'=>255],
			['create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['event_id, result_field, value, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
			'event' => [self::BELONGS_TO, 'SportEvent', 'event_id'],
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'event_id' => null,
			'result_field' => Yii::t('app', 'Result Field'),
			'value' => Yii::t('app', 'Value'),
			'create_at' => Yii::t('app', 'Create At'),
			'event' => null,
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('result_field', $this->result_field, true);
		$criteria->compare('value', $this->value);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}