<?php

/**
 * This is the model base class for the table "team".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Team".
 *
 * Columns in table "team" available as properties of the model,
 * followed by relations of table "team" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $aliases_count
 * @property integer $update_at
 * @property integer $create_at
 *
 * @property TeamAlias[] $teamAliases
 */
abstract class BaseTeam extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'team';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Team|Teams', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return [
			['title', 'required'],
			['aliases_count, update_at, create_at', 'numerical', 'integerOnly'=>true],
			['title', 'length', 'max'=>255],
			['aliases_count, update_at, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, title, aliases_count, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
			'teamAliases' => [self::HAS_MANY, 'TeamAlias', 'team_id'],
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'aliases_count' => Yii::t('app', 'Aliases Count'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
			'teamAliases' => null,
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('aliases_count', $this->aliases_count);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}