<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $game_id
 * @property string $align
 * @property string $klan
 * @property string $login
 * @property integer $level
 * @property float $kr_balance
 * @property float $ekr_balance
 * @property string $voucher_balance
 * @property string $gold_balance
 * @property integer $update_at
 * @property integer $create_at
 * @property integer $active_balance
 * @property string $extra_ratio
 * @property string $admin_comment
 *
 */
abstract class BaseUser extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'login';
	}

	public function rules() {
		return [
			['game_id, login', 'required'],
			['game_id, level, update_at, create_at, active_balance', 'numerical', 'integerOnly'=>true],
			['align, klan, login', 'length', 'max'=>255],
			['kr_balance, ekr_balance, voucher_balance, gold_balance, extra_ratio', 'length', 'max'=>19],
			['admin_comment', 'safe'],
			['align, klan, level, kr_balance, ekr_balance, voucher_balance, gold_balance, update_at, create_at, active_balance, extra_ratio, admin_comment', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, game_id, align, klan, login, level, kr_balance, ekr_balance, voucher_balance, gold_balance, update_at, create_at, active_balance, extra_ratio, admin_comment', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'game_id' => Yii::t('app', 'Game'),
			'align' => Yii::t('app', 'Align'),
			'klan' => Yii::t('app', 'Klan'),
			'login' => Yii::t('app', 'Login'),
			'level' => Yii::t('app', 'Level'),
			'kr_balance' => Yii::t('app', 'Kr Balance'),
			'ekr_balance' => Yii::t('app', 'Ekr Balance'),
			'voucher_balance' => Yii::t('app', 'Voucher Balance'),
			'gold_balance' => Yii::t('app', 'Gold Balance'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
			'active_balance' => Yii::t('app', 'Active Balance'),
			'extra_ratio' => Yii::t('app', 'Extra Ratio'),
			'admin_comment' => Yii::t('app', 'Admin Comment'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('align', $this->align, true);
		$criteria->compare('klan', $this->klan, true);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('level', $this->level);
		$criteria->compare('kr_balance', $this->kr_balance, true);
		$criteria->compare('ekr_balance', $this->ekr_balance, true);
		$criteria->compare('voucher_balance', $this->voucher_balance, true);
		$criteria->compare('gold_balance', $this->gold_balance, true);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);
		$criteria->compare('active_balance', $this->active_balance);
		$criteria->compare('extra_ratio', $this->extra_ratio, true);
		$criteria->compare('admin_comment', $this->admin_comment, true);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}