<?php

/**
 * This is the model base class for the table "team_alias_new".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TeamAliasNew".
 *
 * Columns in table "team_alias_new" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property integer $find_at
 *
 */
abstract class BaseTeamAliasNew extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'team_alias_new';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TeamAliasNew|TeamAliasNews', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return [
			['title', 'required'],
			['find_at', 'numerical', 'integerOnly'=>true],
			['title', 'length', 'max'=>255],
			['find_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, title, find_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'find_at' => Yii::t('app', 'Find At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('find_at', $this->find_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}