<?php

/**
 * This is the model base class for the table "user_history_sport".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserBetting".
 *
 * Columns in table "user_history_sport" available as properties of the model,
 * followed by relations of table "user_history_sport" available as properties of the model.
 *
 * @property integer $id
 * @property integer $event_id
 * @property integer $user_id
 * @property integer $bet_group_id
 * @property string $price
 * @property integer $price_type
 * @property string $ratio_type
 * @property string $ratio_value
 * @property integer $status
 * @property integer $result_status
 * @property integer $_v
 * @property integer $update_at
 * @property integer $create_at
 * @property string $create_at_datetime
 *
 * @property BettingGroup $betGroup
 */
abstract class BaseUserBetting extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_betting';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserBetting', $n);
	}

	public static function representingColumn() {
		return 'ratio_type';
	}

	public function rules() {
		return [
			['event_id, user_id, bet_group_id, price_type, ratio_type, ratio_value, _v', 'required'],
			['event_id, user_id, bet_group_id, price_type, status, result_status, _v, update_at, create_at', 'numerical', 'integerOnly'=>true],
			['price, ratio_value', 'length', 'max'=>19],
			['ratio_type', 'length', 'max'=>255],
			['create_at_datetime', 'safe'],
			['price, update_at, create_at, create_at_datetime', 'default', 'setOnEmpty' => true, 'value' => null],
			['id, event_id, user_id, bet_group_id, price, price_type, ratio_type, ratio_value, status, result_status, _v, update_at, create_at, create_at_datetime', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
			'betGroup' => [self::BELONGS_TO, 'BettingGroup', 'bet_group_id'],
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'user_id' => Yii::t('app', 'User'),
			'bet_group_id' => null,
			'price' => Yii::t('app', 'Price'),
			'price_type' => Yii::t('app', 'Price Type'),
			'ratio_type' => Yii::t('app', 'Ratio Type'),
			'ratio_value' => Yii::t('app', 'Ratio Value'),
			'status' => Yii::t('app', 'Status'),
			'result_status' => Yii::t('app', 'Result Status'),
			'_v' => null,
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
			'create_at_datetime' => Yii::t('app', 'Create At Datetime'),
			'event' => null,
			'v' => null,
			'betGroup' => null,
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('bet_group_id', $this->bet_group_id);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('price_type', $this->price_type);
		$criteria->compare('ratio_type', $this->ratio_type, true);
		$criteria->compare('ratio_value', $this->ratio_value, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('result_status', $this->result_status);
		$criteria->compare('_v', $this->_v);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);
		$criteria->compare('create_at_datetime', $this->create_at_datetime, true);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}