<?php

/**
 * This is the model base class for the table "proxy_list".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Akcii".
 *
 * Columns in table "akcii" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $ip
 * @property integer $port
 * @property integer $delay
 * @property string $country_code
 * @property string $country_name
 * @property boolean $is_enable
 * @property integer $update_at
 * @property integer $create_at
 *
 */
abstract class BaseProxyList extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'proxy_list';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Proxy|Proxies', $n);
	}

	public static function representingColumn() {
		return 'ip';
	}

	public function rules() {
		return [
			['ip, port', 'required'],
			['port, delay, update_at, create_at', 'numerical', 'integerOnly'=>true],
			['ip, port, delay, country_code, country_name, is_enable, update_at, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'ip' => Yii::t('app', 'Ip'),
			'port' => Yii::t('app', 'Port'),
			'delay' => Yii::t('app', 'Delay'),
			'country_code' => Yii::t('app', 'Country Code'),
			'country_name' => Yii::t('app', 'Country Name'),
			'is_enable' => Yii::t('app', 'Is Enable'),
			'update_at' => Yii::t('app', 'Update At'),
			'create_at' => Yii::t('app', 'Create At'),
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('port', $this->port);
		$criteria->compare('delay', $this->delay);
		$criteria->compare('country_code', $this->country_code, true);
		$criteria->compare('country_name', $this->country_name, true);
		$criteria->compare('is_enable', $this->is_enable);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}