<?php

/**
 * This is the model base class for the table "sport_event_ratio_additional".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SportEventRatio".
 *
 * Columns in table "sport_event_ratio_additional" available as properties of the model,
 * followed by relations of table "sport_event_ratio_additional" available as properties of the model.
 *
 * @property integer $event_id
 * @property string $type
 * @property integer $_v
 * @property string $value
 * @property integer $create_at
 *
 * @property SportEvent $event
 */
abstract class BaseSportEventRatio extends BaseModel {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sport_event_ratio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SportEventRatio|SportEventRatios', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return [
			['event_id, type, value', 'required'],
			['event_id, _v, create_at', 'numerical', 'integerOnly'=>true],
			['type', 'length', 'max'=>255],
			['value', 'length', 'max'=>19],
			['_v, create_at', 'default', 'setOnEmpty' => true, 'value' => null],
			['event_id, type, _v, value, create_at', 'safe', 'on'=>'search'],
		];
	}

	public function relations() {
		return [
			'event' => [self::BELONGS_TO, 'SportEvent', 'event_id'],
		];
	}

	public function pivotModels() {
		return [
		];
	}

	public function attributeLabels() {
		return [
			'event_id' => null,
			'type' => Yii::t('app', 'Type'),
			'_v' => Yii::t('app', 'V'),
			'value' => Yii::t('app', 'Value'),
			'create_at' => Yii::t('app', 'Create At'),
			'event' => null,
		];
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('_v', $this->_v);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('create_at', $this->create_at);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}